USE BIZ_GEN
GO

CREATE NONCLUSTERED INDEX [IX_TB_GEN_CLIPROV_02]
ON [dbo].[TB_GEN_CLIPROV] ([CCI_EMPRESA], CCI_CLIPROV, CNO_CLIPROV)

--create nonclustered index IX_TB_GEN_CLIPROV_02
--ON dbo.TB_GEN_CLIPROV(cci_empresa, cci_cliprov)
--include(cno_cliprov)


use biz_cnt
go

create nonclustered index IX_TB_BAN_PRO_CMPR_02
on dbo.TB_BAN_PRO_CMPR(CCI_EMPRESA, CMP_CODIGO, COD_PROV, CCI_SUCURSAL)

CREATE NONCLUSTERED INDEX [IX_TB_BAN_PRO_CMPR_03]
ON [dbo].[TB_BAN_PRO_CMPR] ([CCI_EMPRESA],[CCI_SUCURSAL],[CMP_CODIGO])
INCLUDE ([COD_PROV])

CREATE NONCLUSTERED INDEX [IX_TB_BAN_PRO_CMPR_RETENCION_02]
ON [dbo].[TB_BAN_PRO_CMPR_RETENCION] ([CCI_EMPRESA],[CCI_SUCURSAL],[CMP_CODIGO])
INCLUDE (DFM_RETENCION, NCI_RETENCION, ID_LOG_FE, CCI_USUARIO, DFM_PROCESO, CES_FE, CCI_CLAVE_ACCESO)


USE [BIZ_FAC]
GO

CREATE NONCLUSTERED INDEX [IX_TB_FAC_FE_PARAMETROS_01]
ON [dbo].[TB_FAC_FE_PARAMETROS] ([CCI_EMPRESA])
include(dfm_fecha_inicio)

CREATE NONCLUSTERED INDEX [IX_TB_FAC_FACTURA_17]
ON [dbo].[TB_FAC_FACTURA] ([CCI_EMPRESA],[CCI_TIPOCMPR],[CES_FACTURA],[DFM_FECHA])
INCLUDE ([CCI_CLIENTE],[DFX_REG_FECHA],[CCI_USUARIO],[CES_FE],[CCI_CLAVE_ACCESO],[ID_LOG_FE])
GO

--
--CREATE NONCLUSTERED INDEX [IX_TB_FAC_FACTURA_16]
--ON [dbo].[TB_FAC_FACTURA] ([CCI_TIPOCMPR],[CES_FACTURA],[DFM_FECHA])
--INCLUDE ([CCI_CLIENTE],[DFX_REG_FECHA],[CCI_USUARIO],[CES_FE],[CCI_CLAVE_ACCESO],[ID_LOG_FE])
--GO

--drop index IX_TB_FAC_FACTURA_16
--ON [dbo].[TB_FAC_FACTURA]


CREATE NONCLUSTERED INDEX [IX_TB_FAC_FACTURA_18]
ON [dbo].[TB_FAC_FACTURA] ([CCI_EMPRESA],[CCI_TIPOCMPR],[CCI_CLIENTE],[CES_FACTURA],[DFM_FECHA])
INCLUDE ([DFX_REG_FECHA],[CCI_USUARIO],[CES_FE],[CCI_CLAVE_ACCESO],[ID_LOG_FE])
GO




USE [BIZ_FAC]
GO
CREATE NONCLUSTERED INDEX [IX_TB_FAC_FACTURA_19]
ON [dbo].[TB_FAC_FACTURA] ([CCI_TIPOCMPR],[CES_FACTURA],[CCI_EMPRESA])
INCLUDE ([CCI_CLIENTE],[DFM_FECHA],[DFX_REG_FECHA],[CCI_USUARIO],[CES_FE],[CCI_CLAVE_ACCESO],[ID_LOG_FE])
GO


--

---------------------------
/*
USE BIZ_GEN
GO

drop index IX_TB_GEN_CLIPROV_02
on dbo.TB_GEN_CLIPROV

use biz_cnt
go

drop index IX_TB_BAN_PRO_CMPR_02
on dbo.TB_BAN_PRO_CMPR

drop index IX_TB_BAN_PRO_CMPR_03
on dbo.TB_BAN_PRO_CMPR

drop index IX_TB_BAN_PRO_CMPR_RETENCION_02
on dbo.TB_BAN_PRO_CMPR_RETENCION

use BIZ_FAC
go

drop index IX_TB_FAC_FE_PARAMETROS_01
on dbo.TB_FAC_FE_PARAMETROS

drop index IX_TB_FAC_FACTURA_17
on dbo.TB_FAC_FACTURA

drop index IX_TB_FAC_FACTURA_18
ON [dbo].[TB_FAC_FACTURA]

drop index IX_TB_FAC_FACTURA_19
ON [dbo].[TB_FAC_FACTURA]

https://stackoverflow.com/questions/39383685/primeng-datatable-checkbox-selection-with-pagination

*/