USE BIZ_GEN
GO

CREATE NONCLUSTERED INDEX [IX_TB_GEN_CLIPROV_02]
ON [dbo].[TB_GEN_CLIPROV] ([CCI_EMPRESA], CCI_CLIPROV, CNO_CLIPROV)

--create nonclustered index IX_TB_GEN_CLIPROV_02
--ON dbo.TB_GEN_CLIPROV(cci_empresa, cci_cliprov)
--include(cno_cliprov)


use biz_cnt
go

create nonclustered index IX_TB_BAN_PRO_CMPR_02
on dbo.TB_BAN_PRO_CMPR(CCI_EMPRESA, CMP_CODIGO, COD_PROV, CCI_SUCURSAL)

CREATE NONCLUSTERED INDEX [IX_TB_BAN_PRO_CMPR_03]
ON [dbo].[TB_BAN_PRO_CMPR] ([CCI_EMPRESA],[CCI_SUCURSAL],[CMP_CODIGO])
INCLUDE ([COD_PROV])

CREATE NONCLUSTERED INDEX [IX_TB_BAN_PRO_CMPR_RETENCION_02]
ON [dbo].[TB_BAN_PRO_CMPR_RETENCION] ([CCI_EMPRESA],[CCI_SUCURSAL],[CMP_CODIGO])
INCLUDE (DFM_RETENCION, NCI_RETENCION, ID_LOG_FE, CCI_USUARIO, DFM_PROCESO, CES_FE, CCI_CLAVE_ACCESO)


USE [BIZ_FAC]
GO

CREATE NONCLUSTERED INDEX [IX_TB_FAC_FE_PARAMETROS_01]
ON [dbo].[TB_FAC_FE_PARAMETROS] ([CCI_EMPRESA])
include(dfm_fecha_inicio)

CREATE NONCLUSTERED INDEX [IX_TB_FAC_FACTURA_17]
ON [dbo].[TB_FAC_FACTURA] ([CCI_EMPRESA],[CCI_TIPOCMPR],[CES_FACTURA],[DFM_FECHA])
INCLUDE ([CCI_CLIENTE],[DFX_REG_FECHA],[CCI_USUARIO],[CES_FE],[CCI_CLAVE_ACCESO],[ID_LOG_FE])
GO

--
--CREATE NONCLUSTERED INDEX [IX_TB_FAC_FACTURA_16]
--ON [dbo].[TB_FAC_FACTURA] ([CCI_TIPOCMPR],[CES_FACTURA],[DFM_FECHA])
--INCLUDE ([CCI_CLIENTE],[DFX_REG_FECHA],[CCI_USUARIO],[CES_FE],[CCI_CLAVE_ACCESO],[ID_LOG_FE])
--GO

--drop index IX_TB_FAC_FACTURA_16
--ON [dbo].[TB_FAC_FACTURA]


CREATE NONCLUSTERED INDEX [IX_TB_FAC_FACTURA_18]
ON [dbo].[TB_FAC_FACTURA] ([CCI_EMPRESA],[CCI_TIPOCMPR],[CCI_CLIENTE],[CES_FACTURA],[DFM_FECHA])
INCLUDE ([DFX_REG_FECHA],[CCI_USUARIO],[CES_FE],[CCI_CLAVE_ACCESO],[ID_LOG_FE])
GO




USE [BIZ_FAC]
GO
CREATE NONCLUSTERED INDEX [IX_TB_FAC_FACTURA_19]
ON [dbo].[TB_FAC_FACTURA] ([CCI_TIPOCMPR],[CES_FACTURA],[CCI_EMPRESA])
INCLUDE ([CCI_CLIENTE],[DFM_FECHA],[DFX_REG_FECHA],[CCI_USUARIO],[CES_FE],[CCI_CLAVE_ACCESO],[ID_LOG_FE])
GO


--

---------------------------
/*
USE BIZ_GEN
GO

drop index IX_TB_GEN_CLIPROV_02
on dbo.TB_GEN_CLIPROV

use biz_cnt
go

drop index IX_TB_BAN_PRO_CMPR_02
on dbo.TB_BAN_PRO_CMPR

drop index IX_TB_BAN_PRO_CMPR_03
on dbo.TB_BAN_PRO_CMPR

drop index IX_TB_BAN_PRO_CMPR_RETENCION_02
on dbo.TB_BAN_PRO_CMPR_RETENCION

use BIZ_FAC
go

drop index IX_TB_FAC_FE_PARAMETROS_01
on dbo.TB_FAC_FE_PARAMETROS

drop index IX_TB_FAC_FACTURA_17
on dbo.TB_FAC_FACTURA

drop index IX_TB_FAC_FACTURA_18
ON [dbo].[TB_FAC_FACTURA]

drop index IX_TB_FAC_FACTURA_19
ON [dbo].[TB_FAC_FACTURA]

https://stackoverflow.com/questions/39383685/primeng-datatable-checkbox-selection-with-pagination

ALTER view [dbo].[VI_FAC_FE_DOCUMENTOS]
AS
SELECT f.cci_empresa, 
(select cno_empresa from BIZ_GEN..tb_seg_empresa where CCI_EMPRESA = f.CCI_EMPRESA) as cno_empresa,
f.cci_sucursal, 
f.cci_cliente, 
f.cno_cliprov,
f.dfm_fecha,
f.cci_tipocmpr, 
case f.cci_tipocmpr when 'FAC' then 'FACTURA' when 'NC' then 'NOTA DE CREDITO' when 'RET' then 'RETENCION' when 'GUI' then 'GUIA' end as descripcion_cci_tipocmpr,
f.nci_documento,
f.id_log_fe,
f.cci_usuario,
--f.dfx_reg_fecha,
f.ces_fe,
case f.ces_fe when 'P' then 'PENDIENTE' when 'G' then 'GENERADO' when 'F' then 'FIRMADO' when 'E' then 'ENVIADO' when 'A' then 'AUTORIZADO' when 'R' then 'RECHAZADO' end as descripcion_ces_fe,
f.cci_clave_acceso,
f.ambiente
FROM (  
	SELECT F.CCI_EMPRESA, 
			F.CCI_SUCURSAL, 
			F.CCI_CLIENTE, 
			c.cno_cliprov,
			F.DFM_FECHA,
			F.CCI_TIPOCMPR, 
			F.NCI_FACTURA AS NCI_DOCUMENTO,
			F.ID_LOG_FE,
			F.CCI_USUARIO,
			--F.DFX_REG_FECHA,
			F.CES_FE,
			F.CCI_CLAVE_ACCESO,
			PFE.AMBIENTE
	FROM BIZ_FAC..TB_FAC_FACTURA F INNER JOIN BIZ_FAC..TB_FAC_FE_PARAMETROS PFE ON
	F.CCI_EMPRESA = PFE.CCI_EMPRESA	 INNER JOIN BIZ_GEN..TB_GEN_CLIPROV C with(forceseek) ON 
	F.CCI_EMPRESA = C.CCI_EMPRESA
	AND F.CCI_CLIENTE = C.CCI_CLIPROV
	WHERE f.CCI_EMPRESA != ''
	and F.CCI_TIPOCMPR = 'FAC'
	AND F.CES_FACTURA IS NULL
	and F.DFM_FECHA >= PFE.DFM_FECHA_INICIO
	and PFE.CCI_EMPRESA != ''

union

	SELECT F.CCI_EMPRESA, 
			F.CCI_SUCURSAL, 
			F.CCI_CLIENTE, 
			c.cno_cliprov,
			F.DFM_FECHA,
			F.CCI_TIPOCMPR, 
			F.NCI_FACTURA AS NCI_DOCUMENTO,
			F.ID_LOG_FE,
			F.CCI_USUARIO,
			--F.DFX_REG_FECHA,
			F.CES_FE,
			F.CCI_CLAVE_ACCESO,
			PFE.AMBIENTE
	FROM BIZ_FAC..TB_FAC_FACTURA F INNER JOIN BIZ_FAC..TB_FAC_FE_PARAMETROS PFE ON
	F.CCI_EMPRESA = PFE.CCI_EMPRESA	 INNER JOIN BIZ_GEN..TB_GEN_CLIPROV C with(forceseek) ON 
	F.CCI_EMPRESA = C.CCI_EMPRESA
	AND F.CCI_CLIENTE = C.CCI_CLIPROV
	WHERE f.CCI_EMPRESA != ''
	and F.CCI_TIPOCMPR = 'NC'
	AND F.CES_FACTURA IS NULL
	and F.DFM_FECHA >= PFE.DFM_FECHA_INICIO
	and PFE.CCI_EMPRESA != ''

union

SELECT DISTINCT R.CCI_EMPRESA,
        R.CCI_SUCURSAL,
        CMPR.COD_PROV AS CCI_CLIENTE,
		c.cno_cliprov,
        R.DFM_RETENCION,
        'RET' AS CCI_TIPOCMPR,
        R.NCI_RETENCION AS NCI_DOCUMENTO,
        R.ID_LOG_FE,
        R.CCI_USUARIO,
        --R.DFM_PROCESO,
        R.CES_FE,
        R.CCI_CLAVE_ACCESO,
		PFE.AMBIENTE
FROM BIZ_CNT..TB_BAN_PRO_CMPR CMPR WITH(NOLOCK) INNER JOIN BIZ_CNT..TB_BAN_PRO_CMPR_RETENCION R WITH(NOLOCK) ON
CMPR.CCI_EMPRESA = R.CCI_EMPRESA
AND CMPR.CCI_SUCURSAL = R.CCI_SUCURSAL
AND CMPR.CMP_CODIGO = R.CMP_CODIGO INNER JOIN BIZ_FAC..TB_FAC_FE_PARAMETROS PFE ON
		R.CCI_EMPRESA = PFE.CCI_EMPRESA INNER JOIN BIZ_GEN..TB_GEN_CLIPROV C with(forceseek) ON 
CMPR.CCI_EMPRESA = C.CCI_EMPRESA
AND CMPR.COD_PROV = C.CCI_CLIPROV
where r.CCI_EMPRESA != ''
and R.DFM_RETENCION >= PFE.DFM_FECHA_INICIO
and PFE.CCI_EMPRESA != ''

union

 SELECT R.CCI_EMPRESA,
        R.CCI_SUCURSAL,	
        R.CCI_CLIENTE,
		c.cno_cliprov,
        R.DFM_EMISION,
        'GUI' AS CCI_TIPOCMPR,
        R.NCI_GUIA AS NCI_DOCUMENTO,
        R.ID_LOG_FE,
        R.CCI_USUARIO,
        --R.DFM_REGISTRO,
        R.CES_FE,
        R.CCI_CLAVE_ACCESO,
		PFE.AMBIENTE
FROM BIZ_INV_REP..TB_INV_GUIA_REMISION R INNER JOIN BIZ_FAC..TB_FAC_FE_PARAMETROS PFE ON
R.CCI_EMPRESA = PFE.CCI_EMPRESA INNER JOIN BIZ_GEN..TB_GEN_CLIPROV C with(forceseek) ON 
R.CCI_EMPRESA = C.CCI_EMPRESA
AND R.CCI_CLIENTE = C.CCI_CLIPROV
where PFE.CCI_EMPRESA != ''
and R.DFM_EMISION >= PFE.DFM_FECHA_INICIO
) F
GO

https://code.tutsplus.com/es/tutorials/how-to-use-map-filter-reduce-in-javascript--cms-26209
https://medium.com/poka-techblog/simplify-your-javascript-use-map-reduce-and-filter-bd02c593cc2d
https://www.quora.com/How-do-you-check-if-an-array-is-empty-in-JavaScript
https://ed.team/blog/javascript-filtrar-elementos-de-un-array-con-filter
https://alligator.io/js/filter-array-method/
https://stackoverflow.com/questions/8073673/how-can-i-add-new-array-elements-at-the-beginning-of-an-array-in-javascript
https://www.w3schools.com/jsref/jsref_unshift.asp
*/